// services/sriLankanMeals.js
// TheMealDB doesn't have a dedicated "Sri Lankan" area filter, so instead
// we keep a curated list of popular Sri Lankan dish names here and search
// TheMealDB for each one by name. Any that TheMealDB doesn't have simply
// won't appear - this list is just a starting point for the "Sri Lankan
// Favorites" section on the Home page.

export const SRI_LANKAN_DISH_NAMES = [
  "Kottu",
  "Hoppers",
  "Pol Sambol",
  "Rice and Curry",
  "Watalappan",
  "Lamprais",
  "Dhal Curry",
  "Fish Ambul Thiyal",
  "String Hoppers",
  "Pittu",
  "Kiribath",
  "Pol Roti",
  "Godamba Roti",
  "Parippu Wade",
  "Isso Wade",
  "Ulundu Vadai",
  "Vegetable Roti",
  "Egg Roti",
  "Kukul Mas Curry",
  "Devilled Chicken",
  "Devilled Fish",
  "Devilled Prawns",
  "Jaffna Crab Curry",
  "Sri Lankan Fish Curry",
  "Sri Lankan Chicken Curry",
  "Sri Lankan Beef Curry",
  "Black Pork Curry",
  "Mutton Curry",
  "Cashew Curry",
  "Jackfruit Curry",
  "Young Jackfruit Curry",
  "Brinjal Moju",
  "Wambatu Moju",
  "Beetroot Curry",
  "Gotu Kola Sambol",
  "Mallung",
  "Kankun Mallung",
  "Parippu Mallung",
  "Seeni Sambol",
  "Lunu Miris",
  "Katta Sambol",
  "Achcharu",
  "Sri Lankan Pickles",
  "Kiri Hodi",
  "Polos Curry",
  "Kola Kenda",
  "Thala Guli",
  "Kokis",
  "Kavum",
  "Athirasa",
  "Aluwa",
  "Pani Pol",
  "Bibikkan",
];
